### ISSUE TITLE
MICS 6814  CO/NO2/NH3 

### ISSUE THREAD

**Issue by empierre** [empierre/arduino#10]
MICS 6814  CO/NO2/NH3 triple sensor http://www.seeedstudio.com/depot/Grove-Multichannel-Gas-Sensor-p-2502.html

**Comment by empierre** [comment]
http://sgx.cdistore.com/datasheets/e2v/MiCS-6814.pdf

**Comment by empierre** [comment]
script validated

**Comment by empierre** [comment]
script validated

**Comment by kalon33** [comment]
@empierre Do you by any chance know how I can use this module when it is not interfaced through I2C, like this [one](https://www.aliexpress.com/item/MICS-6814-Air-quality-CO-VOC-NH3-Nitrogen-oxides-Gas-sensor-1000ppm/32731579562.html) ?

**Comment by empierre** [comment]
it is a real problem, bord I used has beenhaving issues for some years, and now it requires a complex flashing update(requiring soldering) without knowing if it will better works ...

**Comment by kalon33** [comment]
@empierre what do you mean?

**Comment by empierre** [comment]
please see

https://github.com/Seeed-Studio/Mutichannel_Gas_Sensor/issues/2

**Comment by ramchoj** [comment]
I try to interface a MICS 6814 based board like this one 13, without I2C support, with an arduino compatible board. I looked for a library supporting it, but I couldn’t find anything except code for the I2C interfaced sensor.

Did anybody used that sensor before and know how I may use it?

Thanks for your help.

**Comment by sulochanaudawela** [comment]
I am trying the same thing without the I2C interface. I get normal analog reads and convert into that signal to ppm range mentioned in Datasheet. But I've always got 0 sensors reading for CO. There is no issue with Arduino or Wiring.


![image](https://user-images.githubusercontent.com/42551146/63216621-90f70700-c155-11e9-883e-44270a185048.png)

code :
int sensorPin1 = A2;    // select the input pin for the CO
int sensorPin2 = A3;    // select the input pin for the NO2
int sensorValue1 = 0;  // variable to store the value coming from the sensor
int sensorValue2 = 0;
float co = 0.0;
float no2 = 0.0;

void setup() {
  // declare the ledPin as an OUTPUT:
  pinMode(sensorPin1, INPUT);
  pinMode(sensorPin2, INPUT);
  Serial.begin(9600);
  Serial.println("initialization") ;
 
}

void loop() {
  // read the value from the sensor:
  
  sensorValue1 = analogRead(sensorPin1);
  sensorValue2 = analogRead(sensorPin2);
  no2 = 0.05+ sensorValue2*((10-0.05)/1023);
  co = 1 + sensorValue1*((1000-1)/1023);
  
  Serial.println("co sensor value = " + String(sensorValue1)) ;
  Serial.print("CO ppm = ") ;
  Serial.print(co,4);
  Serial.println("");
  Serial.println("no2 sensor value = " + String(sensorValue2)) ;
  Serial.print("NO2 ppm = ") ;
  Serial.println(no2,4);
  delay(3000);
  
  
}

**Comment by isabelkl19** [comment]
Hi, I am working the same way without connecting to the I2C interface but the values give me 0. Any solution?

**Comment by IHOXOHI** [comment]
Hi,
I'm not an expert, but normaly CO is a toxic and rare gaz... If you have "0" value of this gaz, it could be that there isn't CO, which is a good thing...

**Comment by lumes001** [comment]
Good afternoon, I'm working with the sensor without I2c. Has anyone managed to convert the analog signals to ppm?

**Comment by IHOXOHI** [comment]
Hi,
Yes I have, but with micropython.
You can find my report on micropython forum...

Regards,
Sellegri Jérôme.

**Comment by lumes001** [comment]
Good morning, can you send me the link to your microphyton?
________________________________
De: IHOXOHI <notifications@github.com>
Enviado: sexta-feira, 13 de novembro de 2020 04:40
Para: empierre/arduino <arduino@noreply.github.com>
Cc: lumes001 <thiagogiebmeyer@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [empierre/arduino] MICS 6814 CO/NO2/NH3 (#10)


Hi,
Yes I have, but with micropython.
You can find my report on micropython forum...

Regards,
Sellegri Jérôme.

**Comment by IHOXOHI** [comment]
Hi,

https://forum.micropython.org/viewtopic.php?f=14&t=8349

I think that to use correctly this sensor, you need to calibrate it with good proffessional sensor of CO NH3 and NO2 gas.
I have done it correctly for CO gas, but for NH3 and NO2 I haven't a professional sensor and my results are not sure.
The problem is that, pro sensor of NH3 or NO2 are very expansive...
Good luck!
