### ISSUE TITLE
Flood sensor-what type

### ISSUE THREAD

**Issue by pepeEL** [empierre/arduino#22]
Hi
I have a question. What sensor you use to this sketch https://github.com/empierre/arduino/blob/master/FloodSensor.ino

?

**Comment by empierre** [comment]
This could be any of those that trigger a signal on an analog : https://www.mysensors.org/store/water

>  two conductors ;-) well anything you want here it is binary logic, you don't need to mesure the resistance to know how wet it is ...

https://forum.mysensors.org/topic/1721/mysensors-1-5-released/18
