### ISSUE TITLE
DSM501 - Mistake between description and pin assignment

### ISSUE THREAD

**Issue by palhartinger** [empierre/arduino#24]
DustSensor_SamYoung_DSM501.ino

* DESCRIPTION
 *    Pin 2 of dust sensor PM1      -> Digital 3 (PMW)
 *    Pin 4 of dust sensor PM2.5    -> Digital 6 (PWM) 

Pin assignment, does not match the descriptin. Typo mistake...
#define DUST_SENSOR_DIGITAL_PIN_PM10  6 //there must be Digital 3 (PMW) -  PM1
#define DUST_SENSOR_DIGITAL_PIN_PM25  3 //there must be Digital 6 (PWM) - PM2.5

**Comment by empierre** [comment]
correct, changed, thanks !
