### ISSUE TITLE
C2H5OH_terCurve instead of C2H5OH_secCurve for TGS2600

### ISSUE THREAD

**Issue by zoomx** [empierre/arduino#27]
In the sketch AirQuality-Multiple_Gas_Sensor1_4.ino, function MQGetGasPercentage there is this line (553)

`return MQGetPercentage(rs_ro_ratio, ro, C2H5OH_terCurve); //TGS2600`

but in the float definitions for these curves C2H5OH_terCurve is referred to MQ138 (line 104) instead for the TGS2600 the curve should be C2H5OH_terCurve, line 106.

Since the curve coefficients are different, is this an error or not?

**Comment by empierre** [comment]
thanks for pointing, corrected it twice

**Comment by zoomx** [comment]
Same thing in AirQuality-Multiple_Gas_Sensor_console.ino.
I noticed it because I have a TGS2600 so I removed all the others lines and I got an error because I have removed the lines for the MQ138.
