### ISSUE TITLE
mq2 curve value

### ISSUE THREAD

**Issue by JAYON17** [empierre/arduino#29]
Hi may i know how to get these value?
float           COCurve[2]      =  {37793.94418, -3.24294658};   //MQ2
float           H2Curve[2]      =  {957.1355042, -2.07442628};   //MQ2
float           LPGCurve[2]     =  {591.6128784, -1.679699732};  //MQ2
float           SmokeCurve[2]   =  {3426.376355, -2.225037973};  //MQ2

**Comment by empierre** [comment]
please see calculation method on:
https://forum.mysensors.org/topic/147/air-quality-sensor

on this one:
https://github.com/empierre/arduino/blob/master/AirQuality-Multiple_Gas_Sensor1_4.ino

I've written the datasheet link and the curve values

**Comment by JAYON17** [comment]
Alright i got it, beside can you tell me how do you get these 2 value ?
float Ro0 = 4.300; //MQ2 3.83 this has to be tuned 10K Ohm , float RL0 =
2.897; //MQ2 Elecfreacks Octopus

**Comment by empierre** [comment]
values are to be adapted through an initial calibration, if you know gas concentration they you can guess the resistive value to apply
