### ISSUE TITLE
Regarding RL value

### ISSUE THREAD

**Issue by JAYON17** [empierre/arduino#30]
#define         RL_VALUE                     (990) -- Hi may i know the RL value of 990 ohm is suitable for all of the sensor that you used? Because for MQ2 when i refer to datasheet it mentioned the RL value around 5kohm but for the other MQ sensors such as 6 having a 20 kohm

**Comment by empierre** [comment]
This does not work this way, each sensor has its own value ...

**Comment by JAYON17** [comment]
Alright, btw how do you able to get this 2 value 
Ro0 = 4.300;    //MQ2     3.83 this has to be tuned 10K Ohm
RL0 = 2.897;    //MQ2     Elecfreacks Octopus
Can you show me the equation to find this value?

**Comment by empierre** [comment]
some may come from others, remember that no MQ sensor is to be relied on first, and then that no calibration can be done without known gas concentration. 

only the "clean air calibration" method can be used, given you know concentration in the air around you.
