### ISSUE TITLE
Differences among 2 method

### ISSUE THREAD

**Issue by Jackson96** [empierre/arduino#31]
Would you simple tell me the differences between this AirQuality-Multiple_Gas_Sensor1_4.ino projecy compared to http://sandboxelectronics.com/?p=165 -- the mehod used by sandbox in multiple gas callibration? Which one will be more accurate?

**Comment by empierre** [comment]
no MQ sensor is accurate, on my file I tried to combine many based on "clean air calibration method" and datasheet.
